# Generated by Django 3.2.3 on 2021-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
