# Generated by Django 3.2.3 on 2021-05-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
            preserve_default=False,
        ),
    ]
