# Generated by Django 3.2.3 on 2021-05-27 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210527_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='number',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
