# Generated by Django 3.2.3 on 2021-05-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20210527_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetUpWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=15)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='workouts',
            field=models.ManyToManyField(through='workouts.SetUpWorkout', to='workouts.Workout'),
        ),
    ]
