# Generated by Django 3.2.3 on 2021-06-17 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20210528_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.CharField(default=datetime.date.today, max_length=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.CharField(default=datetime.time(9, 0), max_length=5),
        ),
        migrations.AlterField(
            model_name='workoutexercises',
            name='number',
            field=models.CharField(default=15, max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutexercises',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
        ),
    ]
