# Generated by Django 3.2.3 on 2021-06-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20210617_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
