# Generated by Django 3.2.3 on 2021-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workouts',
            field=models.ManyToManyField(related_name='exercises', through='workouts.WorkoutExercises', to='workouts.Workout'),
        ),
    ]
